### ISSUE TITLE
Latitude/Longitude Input Format

### ISSUE THREAD

**Issue by jofwu** [whiterook6/tunguska-event#2]
It seems that Lat/Lon coordinates HAVE to be entered as North and West, using negative values for East/South? Is this intentional? If so, I think making East positive would be best, so that (0,0) is the intersection of the equator and prime meridian.  Though allowing for East/South input might be most clear. 
Not familiar with using Mask to get the fancy input formatting, so I'm not sure if that's feasible. :)

**Comment by jofwu** [comment]
Haven't been able to properly check, but it seems like the program is actually considering positive longitude to be East, even though you've got it labeled West. Which makes sense unless you go out of your way to flip that convention. Just FYI.

**Comment by whiterook6** [comment]
Added support for W/E or N/S -- Using W or S simply flips the actual input. 55N = -55S.
