### ISSUE TITLE
Heading Issue

### ISSUE THREAD

**Issue by jofwu** [whiterook6/tunguska-event#4]
The current default values were giving me some odd results. They are from a hop I did the other night (except longitudes should be East rather than West). It was a large dV and long burn to accurately perform manually, so I definitely got some error. But I got a good shot at the target (couple km off) even with error and planet rotation at play. So looking at these outputs, Pitch and dV seem about right, but the Heading is way off. It was a Southeast jump, not mostly East. :)

I tried a few things to narrow down the problem, and ended up with the following very simple hop:

INPUT:
Start Pos = 10.0 N, 0.0 W
Start Alt = 0m
Target Pos = 0.0 N, 0.0 W
Target Alt = 0m
Body = Mun

OUTPUT:
Heading = 90 deg E of N
Pitch = 12 deg
dV = 1.129 km/s

Without rotation this should be a hop directly to the South, 42.5 deg pitch, and 219 total dV. (per spreadsheet) So you can see the solution here isn't right. I think working out what's causing the heading to be off is the first priority. Fix that and the others might be fine.

I'll try to dig through the math and see where it's going wrong. Will report back if I get a chance to do this.

**Comment by whiterook6** [comment]
Looks like Javascript's Math.atan2 takes y,x while Google Spreadsheet's ATAN2 takes x,y. Simple 90 error.
